// C:\GoProject\src\eShop\errs\category_errors.go

package errs

// import "errors"

// // Определение кастомных ошибок для категорий...
// var (
// 	ErrCategoryAlreadyExists  = errors.New("category already exists")  // Ошибка: категория с таким названием уже существует...
// 	ErrCategoryNotFound       = errors.New("category not found")       // Ошибка: категория не найдена...
// 	ErrCategoryAlreadyDeleted = errors.New("category already deleted") // Ошибка: категория уже удалена...
// 	ErrCategoryNotDeleted     = errors.New("category not deleted")     // Ошибка: категория не была удалена...
// )
