// C:\GoProject\src\eShop\errs\common_errors.go

package errs

// import "errors"

// // Определение общих кастомных ошибок...
// var (
// 	ErrRecordNotFound      = errors.New("record not found")     // Ошибка: запись не найдена...
// 	ErrValidationFailed    = errors.New("validation failed")    // Ошибка: валидация данных не пройдена...
// 	ErrUniquenessViolation = errors.New("uniqueness violation") // Ошибка: нарушение уникальности записи...
// 	ErrSomethingWentWrong  = errors.New("something went wrong") // Ошибка: что-то пошло не так...
// 	ErrUnauthorized        = errors.New("unauthorized")         // Ошибка: неавторизованный доступ...
// 	ErrServerError         = errors.New("server error")         // Ошибка: ошибка сервера...
// )
