// C:\GoProject\src\eShop\errs\errs.go

package errs

import "errors"

// Определение кастомных ошибок, используемых в приложении...
var (
	ErrPermissionDenied            = errors.New("ErrPermissionDenied")            // Ошибка: доступ запрещен...
	ErrValidationFailed            = errors.New("ErrValidationFailed")            // Ошибка: валидация данных не пройдена...
	ErrUsernameUniquenessFailed    = errors.New("ErrUsernameUniquenessFailed")    // Ошибка: имя пользователя должно быть уникальным...
	ErrIncorrectUsernameOrPassword = errors.New("ErrIncorrectUsernameOrPassword") // Ошибка: неверное имя пользователя или пароль...
	ErrRecordNotFound              = errors.New("ErrRecordNotFound")              // Ошибка: запись не найдена...
	ErrUserNotFound                = errors.New("ErrUserNotFound")                // Ошибка: пользователь не найден...
	ErrUsersNotFound               = errors.New("ErrUsersNotFound")               // Ошибка: пользователи не найдены...
	ErrUserAlreadyDeleted          = errors.New("ErrUserAlreadyDeleted")          // Ошибка: пользователь уже был удалён ранее...
	ErrUserNotDeleted              = errors.New("ErrUserNotDeleted")              // Ошибка: пользователь не был удалён...
	ErrSomethingWentWrong          = errors.New("ErrSomethingWentWrong")          // Ошибка: что-то пошло не так...
	ErrUserAlreadyBlocked          = errors.New("ErrUserAlreadyBlocked")          // Ошибка: пользователь уже заблокирован...
	ErrUserNotBlocked              = errors.New("ErrUserNotBlocked")              // Ошибка: пользователь не был заблокирован...
	ErrUnauthorizedPasswordChange  = errors.New("ErrUnauthorizedPasswordChange")  // Ошибка: попытка смены пароля без прав...
	ErrIncorrectPassword           = errors.New("ErrIncorrectPassword")           // Ошибка: неверный старый пароль...
	// Ошибки для сущности Поставщика...
	ErrSupplierAlreadyExists  = errors.New("ErrSupplierAlreadyExists")  // Ошибка: поставщик с таким именем или email уже существует...
	ErrSupplierNotFound       = errors.New("ErrSupplierNotFound")       // Ошибка: поставщик не найден...
	ErrSupplierAlreadyDeleted = errors.New("ErrSupplierAlreadyDeleted") // Ошибка: поставщик уже удалён...
	ErrSupplierNotDeleted     = errors.New("ErrSupplierNotDeleted")     // Ошибка: поставщик не был удалён...
	// Ошибки для сущности Категории...
	ErrCategoryAlreadyExists  = errors.New("ErrCategoryAlreadyExists")  // Ошибка: категория с таким именем уже существует...
	ErrCategoryNotFound       = errors.New("ErrCategoryNotFound")       // Ошибка: категория не найдена...
	ErrCategoryAlreadyDeleted = errors.New("ErrCategoryAlreadyDeleted") // Ошибка: категория уже удалена...
	ErrCategoryNotDeleted     = errors.New("ErrCategoryNotDeleted")     // Ошибка: категория не была удалена...
)
