// C:\GoProject\src\eShop\errs\order_errors.go

package errs

// import "errors"

// // Определение кастомных ошибок для заказов...
// var (
// 	ErrOrderNotFound     = errors.New("order not found")      // Ошибка: заказ не найден...
// 	ErrOrderItemNotFound = errors.New("order item not found") // Ошибка: элемент заказа не найден...
// 	ErrInsufficientStock = errors.New("insufficient stock")   // Ошибка: недостаточно товара на складе...
// 	ErrOrderAlreadyPaid  = errors.New("order already paid")   // Ошибка: заказ уже оплачен...
// )
