// C:\GoProject\src\eShop\errs\product_errors.go

package errs

// import "errors"

// // Определение кастомных ошибок для продуктов...
// var (
// 	ErrProductAlreadyExists  = errors.New("product already exists")      // Ошибка: продукт с таким штрих-кодом уже существует...
// 	ErrProductNotFound       = errors.New("product not found")           // Ошибка: продукт не найден...
// 	ErrProductAlreadyDeleted = errors.New("product already deleted")     // Ошибка: продукт уже удалён...
// 	ErrProductNotDeleted     = errors.New("product not deleted")         // Ошибка: продукт не был удалён...
// 	ErrProductNotWeightBased = errors.New("product is not weight-based") // Ошибка: продукт не основан на весе...
// 	ErrInvalidBarcode        = errors.New("invalid barcode")             // Ошибка: штрих-код не распознан...
// )
