// C:\GoProject\src\eShop\errs\supplier_errors.go

package errs

// import "errors"

// // Определение кастомных ошибок для поставщиков...
// var (
// 	ErrSupplierAlreadyExists  = errors.New("supplier already exists")  // Ошибка: поставщик с таким именем или email уже существует...
// 	ErrSupplierNotFound       = errors.New("supplier not found")       // Ошибка: поставщик не найден...
// 	ErrSupplierAlreadyDeleted = errors.New("supplier already deleted") // Ошибка: поставщик уже удалён...
// 	ErrSupplierNotDeleted     = errors.New("supplier not deleted")     // Ошибка: поставщик не был удалён...
// )
