// C:\GoProject\src\eShop\errs\user_errors.go

package errs

// import "errors"

// // Определение кастомных ошибок для пользователей...
// var (
// 	ErrUserNotFound               = errors.New("user not found")                 // Ошибка: пользователь не найден...
// 	ErrUsersNotFound              = errors.New("users not found")                // Ошибка: пользователи не найдены...
// 	ErrUserAlreadyDeleted         = errors.New("user already deleted")           // Ошибка: пользователь уже был удалён ранее...
// 	ErrUserNotDeleted             = errors.New("user not deleted")               // Ошибка: пользователь не был удалён...
// 	ErrUserAlreadyBlocked         = errors.New("user already blocked")           // Ошибка: пользователь уже заблокирован...
// 	ErrUserNotBlocked             = errors.New("user not blocked")               // Ошибка: пользователь не был заблокирован...
// 	ErrUnauthorizedPasswordChange = errors.New("unauthorized password change")   // Ошибка: попытка смены пароля без прав...
// 	ErrIncorrectPassword          = errors.New("incorrect old password")         // Ошибка: неверный старый пароль...
// 	ErrPermissionDenied           = errors.New("permission denied")              // Ошибка: доступ запрещен...
// 	ErrUsernameUniquenessFailed = errors.New("username must be unique") // Ошибка: имя пользователя должно быть уникальным...
// 	ErrIncorrectUsernameOrPassword = errors.New("incorrect username or password") // Ошибка: неверное имя пользователя или пароль...
// )
