// C:\GoProject\src\eShop\pkg\controllers\routes.go

package controllers

import (
	"eShop/configs"
	_ "eShop/docs"
	"eShop/logger"

	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// localhost:8585/swagger/index.html

// PingPong handles the ping request and responds with a pong message...
func PingPong(c *gin.Context) {
	logger.Info.Printf("Route '%s' called with method '%s'", c.FullPath(), c.Request.Method)
	c.JSON(http.StatusOK, gin.H{
		"message": "pong",
	})
}

func InitRoutes() *gin.Engine {
	router := gin.Default()

	// // Middleware для проверки аутентификации перед логированием
	// router.Use(checkUserAuthentication)
	// // Middleware to log all requests
	// router.Use(middleware.RequestLoggerMiddleware())

	gin.SetMode(configs.AppSettings.AppParams.GinMode)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.GET("/ping", PingPong)

	authG := router.Group("/auth")
	{
		authG.POST("/sign-in", SignIn)
	}

	selfUserG := router.Group("/users", checkUserAuthentication)
	{
		selfUserG.PATCH("/change-password", ChangeOwnPassword) // Обновление пароля текущего пользователя...
		selfUserG.GET("/settings", GetUserSettingsByID)        // Получение настроек пользователя...
		selfUserG.PATCH("/settings", UpdateUserSettings)       // Обновление настроек пользователя...
	}

	// userG := router.Group("/users")
	userG := router.Group("/users", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired, checkAdminRole)
	{
		userG.POST("", CreateUser)                        // Регистрация нового пользователя...
		userG.GET("", GetAllUsers)                        // Получение списка всех активных пользователей...
		userG.GET("/deleted", GetAllDeletedUsers)         // Получение списка всех удалённых пользователей...
		userG.GET("/:id", GetUserByID)                    // Получение данных пользователя по его ID...
		userG.PATCH("/:id", UpdateUserByID)               // Обновление данных пользователя по его ID...
		userG.PATCH("/:id/block", BlockUserByID)          // Блокировка пользователя по его ID...
		userG.PATCH("/:id/unblock", UnblockUserByID)      // Разблокировка пользователя по его ID...
		userG.PATCH("/:id/restore", RestoreUserByID)      // Восстановление удалённого пользователя...
		userG.DELETE("/:id/soft", SoftDeleteUserByID)     // Софт удаление пользователя по его ID...
		userG.DELETE("/:id/hard", HardDeleteUserByID)     // Полное удаление пользователя по его ID (хард удаление)...
		userG.PATCH("/:id/reset-password", ResetPassword) // Сброс пароля пользователя (доступно только администратору)...
	}

	taxesG := router.Group("/taxes", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired, checkManagerOrAdminRole)
	{
		taxesG.GET("", GetAllTaxes)         // Получение списка всех текущих налогов...
		taxesG.PATCH("/:id", UpdateTaxByID) // Обновление налоговой ставки по ID...
	}

	supplierRoleG := router.Group("/suppliers", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired, checkManagerOrAdminRole)
	{
		supplierRoleG.POST("", CreateSupplier)                    // Регистрация нового поставщика...
		supplierRoleG.PATCH("/:id", UpdateSupplierByID)           // Обновление данных поставщика по его ID...
		supplierRoleG.PATCH("/:id/restore", RestoreSupplierByID)  // Восстановление удалённого поставщика...
		supplierRoleG.DELETE("/:id/soft", SoftDeleteSupplierByID) // Софт удаление поставщика по его ID...
		supplierRoleG.DELETE("/:id/hard", HardDeleteSupplierByID) // Полное удаление поставщика...
	}
	supplierG := router.Group("/suppliers", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		supplierG.GET("", GetAllSuppliers)                // Получение списка всех активных поставщиков...
		supplierG.GET("/deleted", GetAllDeletedSuppliers) // Получение списка всех удалённых поставщиков...
		supplierG.GET("/:id", GetSupplierByID)            // Получение данных поставщика по его ID...
	}

	categoryRoleG := router.Group("/categories", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired, checkManagerOrAdminRole)
	{
		categoryRoleG.POST("", CreateCategory)                    // Регистрация новой категории...
		categoryRoleG.PATCH("/:id", UpdateCategoryByID)           // Обновление данных категории по её ID...
		categoryRoleG.PATCH("/:id/restore", RestoreCategoryByID)  // Восстановление удалённой категории...
		categoryRoleG.DELETE("/:id/soft", SoftDeleteCategoryByID) // Софт удаление категории по её ID...
		categoryRoleG.DELETE("/:id/hard", HardDeleteCategoryByID) // Полное удаление категории...
	}
	categoryG := router.Group("/categories", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		categoryG.GET("", GetAllCategories)                // Получение списка всех активных категорий...
		categoryG.GET("/deleted", GetAllDeletedCategories) // Получение списка всех удалённых категорий...
		categoryG.GET("/:id", GetCategoryByID)             // Получение данных категории по её ID...
	}

	productRoleG := router.Group("/products", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired, checkManagerOrAdminRole)
	{
		productRoleG.POST("", AddProduct)                       // Добавление нового товара...
		productRoleG.PATCH("/:id", UpdateProductByID)           // Обновление товара по ID...
		productRoleG.PATCH("/:id/restore", RestoreProductByID)  // Восстановление удаленного продукта...
		productRoleG.DELETE("/:id/soft", SoftDeleteProductByID) // Мягкое удаление продукта...
		productRoleG.DELETE("/:id/hard", HardDeleteProductByID) // Полное удаление продукта...
	}
	productG := router.Group("/products", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		productG.GET("", GetAllProducts)                       // Просмотр всех товаров...
		productG.GET("/:id", GetProductByID)                   // Просмотр товара по ID...
		productG.GET("/barcode/:barcode", GetProductByBarcode) // Просмотр товара по штрих-коду...
	}

	orderG := router.Group("/orders", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		orderG.POST("", AddOrder)                             // Создание нового заказа...
		orderG.PATCH("/:id/paid", MarkOrderAsPaid)            // Отметка об оплате заказа...
		orderG.DELETE("/:id", DeleteOrder)                    // Маршрут для удаления заказа
		orderG.DELETE("/:id/items/:item_id", DeleteOrderItem) // Удаление товара из заказа...
		orderG.GET("/:id", GetOrderByID)                      // Получение заказа по ID...
		orderG.POST("/add-from-barcode", InsertProductByBarcode)

		orderG.POST("/generate-random/:count", GenerateRandomOrders) // Маршрут для генерации заказов
	}

	returnG := router.Group("/returns", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		returnG.POST("", AddReturnProduct) // Добавление возврата товара...
		returnG.GET("", GetAllReturns)     // Получение списка всех возвратов...
		returnG.GET("/:id", GetReturnByID) // Получение возврата по ID...
	}

	barcodeG := router.Group("/barcode", checkUserAuthentication, checkUserBlocked)
	{
		barcodeG.GET("/generate", GenerateBarcode) // Генерация штрих-кода
	}

	ktuG := router.Group("/ktu", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	{
		ktuG.GET("", GetKTU) // Маршрут для расчета КТУ
	}

	// Маршрут для отчетов...
	// reportG := router.Group("/reports", checkUserAuthentication, checkUserBlocked, CheckPasswordResetRequired)
	reportG := router.Group("/reports")
	{
		reportG.GET("/:report_type", GetReport) // Универсальный маршрут для всех отчётов
	}

	router.POST("/insert-test-data", InsertTestData)

	return router
}
