// C:\GoProject\src\eShop\models\user.go

package models

import "time"

type User struct {
	ID                    uint       `gorm:"primaryKey" json:"id"`                        // Уникальный идентификатор продавца...
	FullName              string     `gorm:"size:255;not null" json:"full_name"`          // Полное имя продавца...
	Username              string     `gorm:"size:255;not null;unique" json:"username"`    // Логин продавца...
	Email                 string     `gorm:"size:255;not null;unique" json:"email"`       // Email продавца...
	Phone                 string     `gorm:"size:15" json:"phone"`                        // Телефон продавца...
	Password              string     `gorm:"size:255;not null" json:"password"`           // Пароль продавца...
	PasswordResetRequired bool       `gorm:"default:true" json:"password_reset_required"` // Флаг обязательной смены пароля после сброса Админом...
	Role                  string     `gorm:"size:50;not null;default:seller" json:"role"` // Роль продавца (например: 'admin', 'manager', 'seller')...
	IsBlocked             bool       `gorm:"default:false" json:"is_blocked"`             // Заблокирован ли продавец...
	BlockedAt             *time.Time `json:"blocked_at"`                                  // Время блокировки продавца...
	CreatedAt             time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"` // Время создания записи...
	UpdatedAt             *time.Time `json:"updated_at"`                                  // Время последнего обновления записи...
	DeletedAt             *time.Time `json:"deleted_at"`                                  // Время удаления записи...
	IsDeleted             bool       `gorm:"default:false" json:"is_deleted"`             // Флаг удаления записи...

	// Связи
	Orders       []Order      `json:"orders"`                                                             // Связь с таблицей заказов, связанных с продавцом...
	UserSettings UserSettings `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"user_settings"` // Связь с таблицей настроек пользователя...
}

func (User) TableName() string {
	return "users"
}

// SwagUser представляет структуру пользователя с основными данными...
type SwagUser struct {
	FullName string `json:"full_name"` // Полное имя пользователя...
	Username string `json:"username"`  // Логин для входа в систему...
	Email    string `json:"email"`     // Адрес электронной почты пользователя...
	Password string `json:"password"`  // Пароль для аутентификации...
}

type SignInInput struct {
	Username string `json:"username" gorm:"unique"`
	Password string `json:"password" gorm:"not null"`
}

// UserResponse представляет укороченную версию модели User для вывода в API
type UserResponse struct {
	ID                    uint       `json:"id"`                      // Уникальный идентификатор продавца...
	FullName              string     `json:"full_name"`               // Полное имя продавца...
	Username              string     `json:"username"`                // Логин продавца...
	Email                 string     `json:"email"`                   // Email продавца...
	Phone                 string     `json:"phone"`                   // Телефон продавца...
	PasswordResetRequired bool       `json:"password_reset_required"` // Флаг обязательной смены пароля...
	Role                  string     `json:"role"`                    // Роль продавца...
	IsBlocked             bool       `json:"is_blocked"`              // Заблокирован ли продавец...
	BlockedAt             *time.Time `json:"blocked_at"`              // Время блокировки продавца...
	CreatedAt             time.Time  `json:"created_at"`              // Время создания записи...
}
